d = 1234-12-31
t = 23:59:60
tm = 23:59:60.1234
dts = 1234-12-31 23:59:60.1234
dtt = 1234-12-31t23:59:60
dtT = 1234-12-31T23:59:60
dtz = 1234-12-31 23:59:60.1234Z
dtop = 1234-12-31 23:59:60.1234+03:59
dton = 1234-12-31 23:59:60-12:00
